spring:
  application:
    admin:
      enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootexam
    username: root
    password: wnsdn13!
  jpa:
    show-sql: true
    database : mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/html
logging:
  level:
    org.hibernate: info
    root: info
    org.springframework.web: debug
server:
  port: 9998